### ISSUE TITLE
user block blocked

### ISSUE THREAD

**Issue by Cabayi** [L235/hat-collector#21]
**Describe the bug**
The bot reports "Sennalen edited", but "Maxim block blocked"

**To reproduce**

**Expected behavior**
It should report "Maxim blocked"

**Console output**

**Environment:**
IRC channel #wikipedia-en-arbcom-enforcement

**Additional context**
13:37 <+hats_beta> Maxim block blocked User:PsycProf (account creation blocked, cannot edit own talk page) with an expiry time of indefinite: {{ArbComBlock}}, appeal only to [arbcom-en@wikimedia.org](mailto:arbcom-en@wikimedia.org) https://en.wikipedia.org/wiki/Special:Redirect/logid/135317350
13:38 <+hats_beta> Sennalen edited [[Wikipedia:Arbitration/Requests/Enforcement]]: /* Request concerning Newimpartial */ reply https://en.wikipedia.org/w/index.php?diff=1105083918

**Comment by L235** [comment]
Hm. I think I'd be ok with dropping line 227, but I'm not certain. It looks like most of the time, the EventStream's `log_action_comment` does start with a verb (`blocked`, `changed block settings`, `uploaded`, etc.). New user accounts aren't -- those use the comment `New user account`. I guess dropping line 227 doesn't lose any information, because the log link is still there.

**Comment by Cabayi** [comment]
I have no opinion other than "block blocked" looks silly. Thanks for looking into it.

**Comment by L235** [comment]
I think spending development effort on building custom messages isn't worth it considering that we could instead spend that effort building better log rule processing (e.g. regex over parameters other than `log_action_comment`). 

I think the best way is to just drop line 227.

And @Cabayi, you're always welcome to join in if you're interested :-)
